### ISSUE TITLE
CSS SyntaxError 

### ISSUE THREAD

**Issue by tracyperangusta** [jquery-ui-rails/jquery-ui-rails#138]
`Step #0 - "buildImage": SassC::SyntaxError: Error: Invalid CSS after "...consContent}*/;": expected expression (e.g. 1px, bold), was "}"
Step #0 - "buildImage":         on line 210:1 of ../opt/rbenv/versions/2.6.8/lib/ruby/gems/2.6.0/gems/jquery-ui-rails-6.0.1/app/assets/stylesheets/jquery-ui/theme.css.erb
Step #0 - "buildImage":         from line 12:9 of app/assets/stylesheets/main.sass
Step #0 - "buildImage":         from line 17:1 of app/assets/stylesheets/application.sass
Step #0 - "buildImage": >> }
Step #0 - "buildImage": 
Step #0 - "buildImage":    ^
Step #0 - "buildImage": /opt/rbenv/versions/2.6.8/lib/ruby/gems/2.6.0/gems/jquery-ui-rails-6.0.1/app/assets/stylesheets/jquery-ui/theme.css.erb:210
Step #0 - "buildImage": /opt/rbenv/versions/2.6.8/lib/ruby/gems/2.6.0/gems/sassc-2.4.0/lib/sassc/engine.rb:50:in `render'
Step #0 - "buildImage": /opt/rbenv/versions/2.6.8/lib/ruby/gems/2.6.0/gems/sassc-rails-2.1.2/lib/sassc/rails/template.rb:40:in `block in call'`

I got this error while executing bundle exec rake assets:precompile.
I use the latest version 6.0.1.

I am really confused with this error. Do you have any idea what is wrong ?

**Comment by tracyperangusta** [comment]
I finally found out a fix. The error was raised because of misdefined ENV variables. Nothing related with the file theme.css.erb.

I close the issue
